import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode, TextareaHTMLAttributes } from 'react';

export function Button({ children, className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement>) { return <button className={`rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50 ${className}`} {...props}>{children}</button>; }
export function Input(props: InputHTMLAttributes<HTMLInputElement>) { return <input className="w-full rounded-md border bg-card px-3 py-2 text-sm outline-none focus:border-primary" {...props} />; }
export function Textarea(props: TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea className="w-full rounded-md border bg-card px-3 py-2 text-sm outline-none focus:border-primary" {...props} />; }
export function Select({ children, ...props }: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select className="w-full rounded-md border bg-card px-3 py-2 text-sm" {...props}>{children}</select>; }
export function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`rounded-xl border bg-card p-6 ${className}`}>{children}</section>; }
export function Badge({ children }: { children: ReactNode }) { return <span className="inline-flex rounded-full bg-muted px-2.5 py-1 text-xs font-medium">{children}</span>; }
export function Progress({ value }: { value: number }) { return <div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary transition-all" style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div>; }
export function Skeleton({ className = '' }: { className?: string }) { return <div className={`animate-pulse rounded-md bg-muted ${className}`} />; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="py-12 text-center"><h2 className="font-semibold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{description}</p></div>; }
export function ErrorState({ title = 'Something went wrong' }: { title?: string }) { return <div role="alert" className="rounded-md border border-red-300 bg-red-50 p-4 text-sm text-red-800">{title}</div>; }
export function Dialog({ open, title, children, onClose }: { open: boolean; title: string; children: ReactNode; onClose: () => void }) { if (!open) return null; return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" role="dialog" aria-modal="true" aria-label={title}><div className="w-full max-w-lg rounded-xl border bg-card p-6"><div className="flex items-center justify-between"><h2 className="font-semibold">{title}</h2><button aria-label="Close" onClick={onClose}>Close</button></div><div className="mt-4">{children}</div></div></div>; }
export function Dropdown({ label, children }: { label: string; children: ReactNode }) { return <details className="relative"><summary className="cursor-pointer list-none rounded-md border px-3 py-2 text-sm">{label}</summary><div className="absolute right-0 z-10 mt-2 min-w-40 rounded-md border bg-card p-2 shadow-lg">{children}</div></details>; }
export function Toast({ message }: { message: string }) { return <div role="status" className="rounded-md border bg-card px-4 py-3 text-sm shadow-lg">{message}</div>; }
export function Tabs({ tabs, active }: { tabs: string[]; active: string }) { return <div role="tablist" className="flex gap-1 border-b">{tabs.map((tab) => <button role="tab" aria-selected={tab === active} className={`border-b-2 px-3 py-2 text-sm ${tab === active ? 'border-primary text-primary' : 'border-transparent text-muted-foreground'}`} key={tab}>{tab}</button>)}</div>; }
